# Generated by Django 3.2.11 on 2022-02-02 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_blogs_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='header_image',
        ),
    ]
